project_name: netex-gtfs-converter

builds:
  - main: ./cmd/netex-gtfs-converter
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: netex-gtfs-converter
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: theoremus-urban-solutions
    name: netex-gtfs-converter

changelog:
  use: git
  sort: asc

checksum:
  name_template: 'checksums.txt'

dist: dist
